import React, { createContext, useContext, useState } from 'react';

export const LANGUAGES = [
  { code: 'en', label: 'English', flag: '🇬🇧' },
  { code: 'hi', label: 'हिन्दी', flag: '🇮🇳' },
  { code: 'ta', label: 'தமிழ்', flag: '🇮🇳' },
  { code: 'te', label: 'తెలుగు', flag: '🇮🇳' },
  { code: 'ml', label: 'മലയാളം', flag: '🇮🇳' },
  { code: 'kn', label: 'ಕನ್ನಡ', flag: '🇮🇳' },
];

export const TRANSLATIONS = {
  en: {
    appName: 'PivotPath',
    dashboard: 'Dashboard',
    aiCoach: 'AI Coach',
    credentials: 'Credentials',
    skillsSignal: 'Skills Signal',
    employers: 'Employers',
    gigMarket: 'Gig Market',
    myISA: 'My ISA',
    profile: 'Profile',
    tests: 'Interview Tests',
    jobs: 'Jobs',
    courses: 'Courses',
    signOut: 'Sign out',
    welcomeBack: 'Welcome back',
    finance: 'Finance',
    currentStatus: 'Current status',
    currentRole: 'Current role',
    targetRole: 'Target role',
    estSalaryUplift: 'Est. salary uplift',
    chatWithCoach: 'Chat with AI Coach',
    browseCredentials: 'Browse Credentials',
    getEnrolled: 'Get enrolled',
    salaryInRupees: 'Salary in ₹',
    topJobs: 'Top Job Openings',
    virtualInterview: 'Virtual Interview',
    startInterview: 'Start Interview',
    freeYoutubeCourses: 'Free YouTube Courses',
    topInDemandSkills: 'Top in-demand skills',
    yourAIRoadmap: 'Your AI roadmap',
    language: 'Language',
    freshers: 'Freshers',
    experienced: 'Experienced',
    allJobs: 'All Jobs',
    financeSector: 'Finance Sector',
  },
  hi: {
    appName: 'PivotPath',
    dashboard: 'डैशबोर्ड',
    aiCoach: 'AI कोच',
    credentials: 'प्रमाणपत्र',
    skillsSignal: 'कौशल संकेत',
    employers: 'नियोक्ता',
    gigMarket: 'गिग बाज़ार',
    myISA: 'मेरा ISA',
    profile: 'प्रोफ़ाइल',
    tests: 'साक्षात्कार परीक्षण',
    jobs: 'नौकरियाँ',
    courses: 'पाठ्यक्रम',
    signOut: 'साइन आउट',
    welcomeBack: 'वापस स्वागत है',
    finance: 'वित्त',
    currentStatus: 'वर्तमान स्थिति',
    currentRole: 'वर्तमान भूमिका',
    targetRole: 'लक्ष्य भूमिका',
    estSalaryUplift: 'अनुमानित वेतन वृद्धि',
    chatWithCoach: 'AI कोच से बात करें',
    browseCredentials: 'प्रमाणपत्र देखें',
    getEnrolled: 'नामांकन करें',
    salaryInRupees: '₹ में वेतन',
    topJobs: 'शीर्ष नौकरियाँ',
    virtualInterview: 'वर्चुअल साक्षात्कार',
    startInterview: 'साक्षात्कार शुरू करें',
    freeYoutubeCourses: 'मुफ़्त YouTube पाठ्यक्रम',
    topInDemandSkills: 'शीर्ष माँग में कौशल',
    yourAIRoadmap: 'आपका AI रोडमैप',
    language: 'भाषा',
    freshers: 'फ्रेशर्स',
    experienced: 'अनुभवी',
    allJobs: 'सभी नौकरियाँ',
    financeSector: 'वित्त क्षेत्र',
  },
  ta: {
    appName: 'PivotPath',
    dashboard: 'டாஷ்போர்ட்',
    aiCoach: 'AI பயிற்சியாளர்',
    credentials: 'சான்றிதழ்கள்',
    skillsSignal: 'திறன் சமிக்ஞை',
    employers: 'முதலாளிகள்',
    gigMarket: 'கிக் சந்தை',
    myISA: 'என் ISA',
    profile: 'சுயவிவரம்',
    tests: 'நேர்காணல் சோதனைகள்',
    jobs: 'வேலைகள்',
    courses: 'பாடநெறிகள்',
    signOut: 'வெளியேறு',
    welcomeBack: 'மீண்டும் வரவேற்கிறோம்',
    finance: 'நிதி',
    currentStatus: 'தற்போதைய நிலை',
    currentRole: 'தற்போதைய பாத்திரம்',
    targetRole: 'இலக்கு பாத்திரம்',
    estSalaryUplift: 'மதிப்பீட்டு சம்பள உயர்வு',
    chatWithCoach: 'AI பயிற்சியாளரிடம் பேசுங்கள்',
    browseCredentials: 'சான்றிதழ்களை உலாவுங்கள்',
    getEnrolled: 'பதிவு செய்யுங்கள்',
    salaryInRupees: '₹ இல் சம்பளம்',
    topJobs: 'சிறந்த வேலை வாய்ப்புகள்',
    virtualInterview: 'மெய்நிகர் நேர்காணல்',
    startInterview: 'நேர்காணல் தொடங்கு',
    freeYoutubeCourses: 'இலவச YouTube பாடங்கள்',
    topInDemandSkills: 'அதிக தேவையுள்ள திறன்கள்',
    yourAIRoadmap: 'உங்கள் AI திட்டவரைபடம்',
    language: 'மொழி',
    freshers: 'புதியவர்கள்',
    experienced: 'அனுபவமுள்ளவர்கள்',
    allJobs: 'அனைத்து வேலைகள்',
    financeSector: 'நிதித் துறை',
  },
  te: {
    appName: 'PivotPath',
    dashboard: 'డాష్‌బోర్డ్',
    aiCoach: 'AI కోచ్',
    credentials: 'క్రెడెన్షియల్స్',
    skillsSignal: 'నైపుణ్య సంకేతం',
    employers: 'యజమానులు',
    gigMarket: 'గిగ్ మార్కెట్',
    myISA: 'నా ISA',
    profile: 'ప్రొఫైల్',
    tests: 'ఇంటర్వ్యూ పరీక్షలు',
    jobs: 'ఉద్యోగాలు',
    courses: 'కోర్సులు',
    signOut: 'సైన్ అవుట్',
    welcomeBack: 'తిరిగి స్వాగతం',
    finance: 'ఫైనాన్స్',
    currentStatus: 'ప్రస్తుత స్థితి',
    currentRole: 'ప్రస్తుత పాత్ర',
    targetRole: 'లక్ష్య పాత్ర',
    estSalaryUplift: 'అంచనా వేతన పెరుగుదల',
    chatWithCoach: 'AI కోచ్‌తో చాట్ చేయండి',
    browseCredentials: 'క్రెడెన్షియల్స్ బ్రౌజ్ చేయండి',
    getEnrolled: 'నమోదు చేయండి',
    salaryInRupees: '₹ లో వేతనం',
    topJobs: 'అగ్రశ్రేణి ఉద్యోగాలు',
    virtualInterview: 'వర్చువల్ ఇంటర్వ్యూ',
    startInterview: 'ఇంటర్వ్యూ ప్రారంభించండి',
    freeYoutubeCourses: 'ఉచిత YouTube కోర్సులు',
    topInDemandSkills: 'అగ్రశ్రేణి డిమాండ్ నైపుణ్యాలు',
    yourAIRoadmap: 'మీ AI రోడ్‌మ్యాప్',
    language: 'భాష',
    freshers: 'నూతన పట్టభద్రులు',
    experienced: 'అనుభవజ్ఞులు',
    allJobs: 'అన్ని ఉద్యోగాలు',
    financeSector: 'ఫైనాన్స్ రంగం',
  },
  ml: {
    appName: 'PivotPath',
    dashboard: 'ഡാഷ്ബോർഡ്',
    aiCoach: 'AI കോച്ച്',
    credentials: 'ക്രെഡൻഷ്യലുകൾ',
    skillsSignal: 'നൈപുണ്യ സിഗ്നൽ',
    employers: 'തൊഴിൽദാതാക്കൾ',
    gigMarket: 'ഗിഗ് മാർക്കറ്റ്',
    myISA: 'എന്റെ ISA',
    profile: 'പ്രൊഫൈൽ',
    tests: 'ഇന്റർവ്യൂ ടെസ്റ്റുകൾ',
    jobs: 'ജോലികൾ',
    courses: 'കോഴ്‌സുകൾ',
    signOut: 'സൈൻ ഔട്ട്',
    welcomeBack: 'തിരിച്ചു സ്വാഗതം',
    finance: 'ധനകാര്യം',
    currentStatus: 'നിലവിലെ സ്ഥിതി',
    currentRole: 'നിലവിലെ റോൾ',
    targetRole: 'ലക്ഷ്യ റോൾ',
    estSalaryUplift: 'ശമ്പള വർദ്ധനവ്',
    chatWithCoach: 'AI കോച്ചുമായി സംസാരിക്കൂ',
    browseCredentials: 'ക്രെഡൻഷ്യലുകൾ കാണൂ',
    getEnrolled: 'ചേരൂ',
    salaryInRupees: '₹ ൽ ശമ്പളം',
    topJobs: 'മികച്ച ജോലി അവസരങ്ങൾ',
    virtualInterview: 'വർച്ചൽ ഇന്റർവ്യൂ',
    startInterview: 'ഇന്റർവ്യൂ ആരംഭിക്കൂ',
    freeYoutubeCourses: 'സൗജന്യ YouTube കോഴ്‌സുകൾ',
    topInDemandSkills: 'ഡിമാൻഡുള്ള നൈപുണ്യങ്ങൾ',
    yourAIRoadmap: 'നിങ്ങളുടെ AI റോഡ്‌മാപ്പ്',
    language: 'ഭാഷ',
    freshers: 'ഫ്രഷർമാർ',
    experienced: 'പരിചയസമ്പന്നർ',
    allJobs: 'എല്ലാ ജോലികൾ',
    financeSector: 'ധനകാര്യ മേഖല',
  },
  kn: {
    appName: 'PivotPath',
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    aiCoach: 'AI ಕೋಚ್',
    credentials: 'ಪ್ರಮಾಣಪತ್ರಗಳು',
    skillsSignal: 'ಕೌಶಲ ಸಂಕೇತ',
    employers: 'ಉದ್ಯೋಗದಾತರು',
    gigMarket: 'ಗಿಗ್ ಮಾರ್ಕೆಟ್',
    myISA: 'ನನ್ನ ISA',
    profile: 'ಪ್ರೊಫೈಲ್',
    tests: 'ಸಂದರ್ಶನ ಪರೀಕ್ಷೆಗಳು',
    jobs: 'ಉದ್ಯೋಗಗಳು',
    courses: 'ಕೋರ್ಸ್‌ಗಳು',
    signOut: 'ಸೈನ್ ಔಟ್',
    welcomeBack: 'ಮತ್ತೆ ಸ್ವಾಗತ',
    finance: 'ಹಣಕಾಸು',
    currentStatus: 'ಪ್ರಸ್ತುತ ಸ್ಥಿತಿ',
    currentRole: 'ಪ್ರಸ್ತುತ ಪಾತ್ರ',
    targetRole: 'ಗುರಿ ಪಾತ್ರ',
    estSalaryUplift: 'ಅಂದಾಜು ವೇತನ ಹೆಚ್ಚಳ',
    chatWithCoach: 'AI ಕೋಚ್‌ನೊಂದಿಗೆ ಮಾತನಾಡಿ',
    browseCredentials: 'ಪ್ರಮಾಣಪತ್ರಗಳನ್ನು ನೋಡಿ',
    getEnrolled: 'ನೋಂದಾಯಿಸಿ',
    salaryInRupees: '₹ ನಲ್ಲಿ ವೇತನ',
    topJobs: 'ಉನ್ನತ ಉದ್ಯೋಗ ಅವಕಾಶಗಳು',
    virtualInterview: 'ವರ್ಚುವಲ್ ಸಂದರ್ಶನ',
    startInterview: 'ಸಂದರ್ಶನ ಪ್ರಾರಂಭಿಸಿ',
    freeYoutubeCourses: 'ಉಚಿತ YouTube ಕೋರ್ಸ್‌ಗಳು',
    topInDemandSkills: 'ಹೆಚ್ಚು ಬೇಡಿಕೆಯ ಕೌಶಲಗಳು',
    yourAIRoadmap: 'ನಿಮ್ಮ AI ರೋಡ್‌ಮ್ಯಾಪ್',
    language: 'ಭಾಷೆ',
    freshers: 'ಫ್ರೆಶರ್ಸ್',
    experienced: 'ಅನುಭವಿಗಳು',
    allJobs: 'ಎಲ್ಲಾ ಉದ್ಯೋಗಗಳು',
    financeSector: 'ಹಣಕಾಸು ವಲಯ',
  },
};

export const LanguageContext = createContext(null);
export const useLanguage = () => useContext(LanguageContext);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('pp_lang') || 'en');

  const setLanguage = (code) => {
    setLang(code);
    localStorage.setItem('pp_lang', code);
  };

  const t = (key) => TRANSLATIONS[lang]?.[key] || TRANSLATIONS['en']?.[key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLanguage, t, languages: LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
}
